name: HAProxyDetector
main: net.andylizi.haproxydetector.bukkit.BukkitMain
version: ${project.version}
authors: [ACJ_DragonDream, andylizi]
load: STARTUP
depend: [ProtocolLib]
# 此插件为通用插件，应支持所有版本的《Minecraft》。
# 如果您遇到关于API版本的错误，请随意将其更改为任何您想要的版本。
api-version: 1.13
awareness:
    - !@UTF8
